name: localglobal

 channels:
  - pytorch
  - defaults

dependencies:
  - cudatoolkit=9.0 # TODO
  - conda=24.5.0  #done 
  - numpy = 1.26.4 #done
  - pip= 24.0 #done
  - Python 3.11.9 #done (need a 3.8-3.11 version for pytorch)
  - pytorch= 2.2.2 #done
  - torchvision= 0.15.2 #done
  - tqdm=4.64.0 # not done yet 
  - pip:
    - wandb==0.12.21 # TODO